# Generated by Django 4.0.5 on 2022-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='НАзвание')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full', models.TextField(verbose_name='Текст ')),
                ('date', models.DateField(verbose_name='дата публикации')),
            ],
        ),
    ]
